version: '3.9'
services:
    app:
        container_name: nextcloud
        ports:
            - '8080:80'
        volumes:
            - './data:/var/www/html'
        restart: unless-stopped
        environment:
            - MEMORY_LIMIT=512M
        networks:
            - nextcloudNET
        image: michivonah/nextcloud
    db:
        container_name: mariadb
        volumes:
            - './db:/var/lib/mysql'
        restart: unless-stopped
        environment:
            - MARIADB_ROOT_PASSWORD=nextcloud
            - MARIADB_DATABASE=nextcloud
            - MARIADB_USER=nextcloud
            - MARIADB_PASSWORD=nextcloud
        networks:
            - nextcloudNET
        image: mariadb
networks:
  nextcloudNET:
    name: nextcloudNET